
// Copyright (c) 2012 Christopher Lux <christopherlux@gmail.com>
// Distributed under the Modified BSD License, see license.txt.

#ifndef SCM_GL_CORE_OPENGL_CONFIG_DEFINES_H_INCLUDED
#define SCM_GL_CORE_OPENGL_CONFIG_DEFINES_H_INCLUDED

#define SCM_GL_CORE_OPENGL_CORE_TYPE            0x01000000u
#define SCM_GL_CORE_OPENGL_ES2_TYPE             0x02000000u

#define SCM_GL_CORE_OPENGL_CORE_VERSION_330     330u
#define SCM_GL_CORE_OPENGL_CORE_VERSION_400     400u
#define SCM_GL_CORE_OPENGL_CORE_VERSION_410     410u
#define SCM_GL_CORE_OPENGL_CORE_VERSION_420     420u
#define SCM_GL_CORE_OPENGL_CORE_VERSION_430     430u
#define SCM_GL_CORE_OPENGL_CORE_VERSION_440     440u

#define SCM_GL_CORE_OPENGL_ES2_VERSION_200      200u

#define SCM_GL_CORE_OPENGL_PLATFORM_MASK        0xFF000000u
#define SCM_GL_CORE_OPENGL_VERSION_MASK         0x0000FFFFu

// OpenGL profile definitions
#define SCM_GL_CORE_OPENGL_330_PROFILE          SCM_GL_CORE_OPENGL_CORE_TYPE | SCM_GL_CORE_OPENGL_CORE_VERSION_330
#define SCM_GL_CORE_OPENGL_400_PROFILE          SCM_GL_CORE_OPENGL_CORE_TYPE | SCM_GL_CORE_OPENGL_CORE_VERSION_400
#define SCM_GL_CORE_OPENGL_410_PROFILE          SCM_GL_CORE_OPENGL_CORE_TYPE | SCM_GL_CORE_OPENGL_CORE_VERSION_410
#define SCM_GL_CORE_OPENGL_420_PROFILE          SCM_GL_CORE_OPENGL_CORE_TYPE | SCM_GL_CORE_OPENGL_CORE_VERSION_420
#define SCM_GL_CORE_OPENGL_430_PROFILE          SCM_GL_CORE_OPENGL_CORE_TYPE | SCM_GL_CORE_OPENGL_CORE_VERSION_430
#define SCM_GL_CORE_OPENGL_440_PROFILE          SCM_GL_CORE_OPENGL_CORE_TYPE | SCM_GL_CORE_OPENGL_CORE_VERSION_440

#define SCM_GL_CORE_OPENGL_ES_200_PROFILE       SCM_GL_CORE_OPENGL_ES2_TYPE  | SCM_GL_CORE_OPENGL_ES2_VERSION_200

#endif // SCM_GL_CORE_OPENGL_CONFIG_DEFINES_H_INCLUDED
