
#ifndef SCM_GL_CORE_OPENGL_CONFIG_CL_H_INCLUDED
#define SCM_GL_CORE_OPENGL_CONFIG_CL_H_INCLUDED

#define SCM_GL_CORE_OPENCL_ENABLE_INTEROP 1
//#undef SCM_GL_CORE_OPENCL_ENABLE_INTEROP

#define SCM_GL_CORE_OPENCL_ENABLE_PROFILING 1
//#undef SCM_GL_CORE_OPENCL_ENABLE_PROFILING

#endif // SCM_GL_CORE_OPENGL_CONFIG_CL_H_INCLUDED
