
#ifndef SCM_CORE_MATH_CONFIG_H_INCLUDED
#define SCM_CORE_MATH_CONFIG_H_INCLUDED

// use float as default value type for all math classes
//  - define SCM_CORE_MATH_FP_PRECISION appropriately
#define SCM_CORE_MATH_FP_PRECISION_SINGLE   0x01
#define SCM_CORE_MATH_FP_PRECISION_DOUBLE   0x02

#define SCM_CORE_MATH_FP_PRECISION  SCM_CORE_MATH_FP_PRECISION_SINGLE

#endif // SCM_CORE_MATH_CONFIG_H_INCLUDED
